//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dewaaiEntities : DbContext
    {
        public dewaaiEntities()
            : base("name=dewaaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cursist> cursist { get; set; }
        public virtual DbSet<cursus> cursus { get; set; }
        public virtual DbSet<schip> schip { get; set; }
        public virtual DbSet<schipklasse> schipklasse { get; set; }
        public virtual DbSet<soortcursus> soortcursus { get; set; }
        public virtual DbSet<werknemers> werknemers { get; set; }
    }
}
