//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class schip
    {
        public int NUMMER { get; set; }
        public Nullable<int> KLASSE { get; set; }
        public string NAAM { get; set; }
        public byte AVERIJ { get; set; }
        public Nullable<int> SOORTCODE { get; set; }
    
        public virtual soortcursus soortcursus { get; set; }
        public virtual schipklasse schipklasse { get; set; }
    }
}
