//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cursu()
        {
            this.cursists = new HashSet<cursist>();
        }
    
        public int CURSUSCODE { get; set; }
        public Nullable<System.DateTime> BEGINDATUM { get; set; }
        public Nullable<System.DateTime> EINDDATUM { get; set; }
        public Nullable<int> SOORTCODE { get; set; }
    
        public virtual soortcursu soortcursu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cursist> cursists { get; set; }
    }
}
