//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cursist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cursist()
        {
            this.cursus = new HashSet<cursu>();
        }
    
        public string EMAILADRES { get; set; }
        public string ROEPNAAM { get; set; }
        public string TUSSENVOEGSEL { get; set; }
        public string ACHTERNAAM { get; set; }
        public string ADRES { get; set; }
        public string WOONPLAATS { get; set; }
        public string TELEFOON { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cursu> cursus { get; set; }
    }
}
