//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class werknemer
    {
        public int WERKNEMERID { get; set; }
        public string GEBRUIKERSNAAM { get; set; }
        public string WACHTWOORD { get; set; }
        public string EMAIL { get; set; }
        public string TELEFOON { get; set; }
    }
}
