//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dewaaiEntities : DbContext
    {
        public dewaaiEntities()
            : base("name=dewaaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cursist> cursists { get; set; }
        public virtual DbSet<cursu> cursus { get; set; }
        public virtual DbSet<schip> schips { get; set; }
        public virtual DbSet<schipklasse> schipklasses { get; set; }
        public virtual DbSet<soortcursu> soortcursus { get; set; }
        public virtual DbSet<werknemer> werknemers { get; set; }
    }
}
